### ISSUE TITLE
what ui editor can be used with gameui?

### ISSUE THREAD

**Issue by fastfading** [martinlindhe/gameui#1]
Is there any game ui editor can be used with gameui lib?
I did not see any in readme

**Comment by martinlindhe** [comment]
None at the moment. I wasn't aware there was such a thing!
Can you recommend one I should have a look at, maybe I can cook something up?

**Comment by fastfading** [comment]
overlap2d   seems to be a good one , according to google search
and I did found a better one

2017-04-09 22:01 GMT+08:00 Martin Lindhe <notifications@github.com>:

**Comment by fastfading** [comment]
and ebiten seems not to be a good choice for now .
as it base on glfw, and ebiten can not build native app for mobile. and it
is not one code base for pc /mobile

maybe u could use gomobile native to build a new gameui.

2017-04-09 22:39 GMT+08:00 hui zhang <fastfading@gmail.com>:

**Comment by martinlindhe** [comment]
Gameui is not meant to be dependant of Ebiten. It renders a image.Image which you can use in any render pipeline, at least that's the idea.

Also, using ebiten you can target desktop, web and mobile using one codebase.

The author even published a game to show how: https://github.com/hajimehoshi/go-inovation
