### ISSUE TITLE
example/tooltip not finding resources

### ISSUE THREAD

**Issue by joeblew99** [martinlindhe/gameui#2]
https://github.com/martinlindhe/gameui/blob/master/examples/tooltip/main.go#L34

````

x-MacBook-Pro:tooltip apple$ go run main.go 
main.go:36: open _resources/gfx/fiveyears.jpg: no such file or directory
````

**Comment by joeblew99** [comment]
i think ebiten does resource embedding ? 
I guess this code is maybe a little behind ebiten API, and needs a little refactoring ?

**Comment by martinlindhe** [comment]
Just follow the readme:

```
Full example using ebiten:

go get github.com/martinlindhe/gameui
cd $GOPATH/src/github.com/martinlindhe/gameui
go run examples/tooltip/main.go
```

No, we are not beind ebiten API. We simply are a different project.
